spring:
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 300000
      connection-timeout: 5000
      pool-name: QuillPool
      data-source-properties:
        socketTimeout: 30
        connectTimeout: 5
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  openapi:
    server-url: https://api.quill.dev

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true

logging:
  structured:
    format:
      console: ecs
