spring:
  application:
    name: quill
  threads:
    virtual:
      enabled: true
  mvc:
    problemdetails:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/quill
    username: quill
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  mail:
    host: localhost
    port: 1025

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,loggers,env,threaddump,heapdump,mappings
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

app:
  base-url: http://localhost:5173
  cors:
    allowed-origins: http://localhost:5173
  jwt:
    secret: Y5JIUo3DKKtevtV4LKYcLiLQwU8AkEXNrTMkWuLdZ+g=
    expiration: 24h
